// Font list sorted alphabetically by name for better UX
export const googleFonts = [
  { name: 'Abhaya Libre', value: 'Abhaya Libre' },
  { name: 'Aboreto', value: 'Aboreto' },
  { name: 'Alegreya', value: 'Alegreya' },
  { name: 'Alex Brush', value: 'Alex Brush' },
  { name: 'Allura', value: 'Allura' },
  { name: 'Arial', value: 'Arial' },
  { name: 'Bitter', value: 'Bitter' },
  { name: 'Cardo', value: 'Cardo' },
  { name: 'Caveat', value: 'Caveat' },
  { name: 'Cookie', value: 'Cookie' },
  { name: 'Cormorant Garamond', value: 'Cormorant Garamond' },
  { name: 'Crimson Text', value: 'Crimson Text' },
  { name: 'Dancing Script', value: 'Dancing Script' },
  { name: 'Great Vibes', value: 'Great Vibes' },
  { name: 'Indie Flower', value: 'Indie Flower' },
  { name: 'Kaushan Script', value: 'Kaushan Script' },
  { name: 'Lato', value: 'Lato' },
  { name: 'Lobster', value: 'Lobster' },
  { name: 'Merriweather', value: 'Merriweather' },
  { name: 'Montserrat', value: 'Montserrat' },
  { name: 'Open Sans', value: 'Open Sans' },
  { name: 'Oswald', value: 'Oswald' },
  { name: 'Pacifico', value: 'Pacifico' },
  { name: 'Playfair Display', value: 'Playfair Display' },
  { name: 'Roboto', value: 'Roboto' },
  { name: 'Sacramento', value: 'Sacramento' },
  { name: 'Satisfy', value: 'Satisfy' },
  { name: 'Verdana', value: 'Verdana' },
  { name: 'Yellowtail', value: 'Yellowtail' },
];

export const fontSizes = [6, 7, 8, 9, 10, 12, 14, 18, 24, 30, 36, 48, 60, 72, 96];